version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    expose:
      - "8000"  # Expose port 8000 for internal communication (no need to map to host)
    depends_on:
      - db
    environment:
      - "DATABASE_HOST=db"

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'fa'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'Galciugun@1*'
      MYSQL_ROOT_PASSWORD: 'Galciugun@1*'
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  nginx:
    image: nginx:latest
    ports:
      - "80:80"  # Map port 80 on host to port 80 on the NGINX container
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Mount a custom NGINX configuration file

volumes:
  mysql_data: